(function attachSql(globalObj) {
  const root = globalObj.DBDesignerCore || (globalObj.DBDesignerCore = {});
  const { formatFieldType } = root;

  function escapeSqlLiteral(value) {
    return String(value ?? "").replaceAll("'", "''");
  }

  function quoteIdentifier(dbType, identifier) {
    if (dbType === "PostgreSQL 14") {
      return `"${String(identifier).replaceAll('"', '""')}"`;
    }
    if (dbType === "MSSQL") {
      return `[${String(identifier).replaceAll("]", "]]")}]`;
    }
    if (dbType === "SQLite") {
      return `"${String(identifier).replaceAll('"', '""')}"`;
    }
    return `\`${String(identifier).replaceAll("`", "``")}\``;
  }

  function buildFieldSqlDefinition(field, dbType) {
    const chunks = [quoteIdentifier(dbType, field.code), formatFieldType(field)];
    const inlineSqliteAutoPk = dbType === "SQLite" && field.autoIncrement && field.primaryKey;
    if (inlineSqliteAutoPk) {
      chunks.push("PRIMARY KEY AUTOINCREMENT");
    } else if (field.notNull || field.primaryKey) {
      chunks.push("NOT NULL");
    }
    if (field.defaultValue && !field.autoIncrement) {
      chunks.push(`DEFAULT ${field.defaultValue}`);
    }
    if (field.autoIncrement) {
      if (dbType === "PostgreSQL 14") {
        chunks.push("GENERATED BY DEFAULT AS IDENTITY");
      } else if (dbType === "MySQL 8") {
        chunks.push("AUTO_INCREMENT");
      } else if (dbType === "MSSQL") {
        chunks.push("IDENTITY(1,1)");
      }
    }
    if (dbType === "MySQL 8" && field.comment) {
      chunks.push(`COMMENT '${escapeSqlLiteral(field.comment)}'`);
    }
    return chunks.join(" ");
  }

  function buildForeignKeyDefinitions(model, table, dbType) {
    const relations = Array.isArray(model?.relations) ? model.relations : [];
    const tables = Array.isArray(model?.tables) ? model.tables : [];
    const defs = [];
    const usedConstraintNames = new Set();

    relations.forEach((relation) => {
      const fk = relation?.foreignKey;
      if (!fk || fk.fromTableId !== table.id) return;

      const referencedTable = tables.find((item) => item.id === fk.toTableId);
      if (!referencedTable) return;
      const fromIds = Array.isArray(fk.fromFieldIds) ? fk.fromFieldIds : [];
      const toIds = Array.isArray(fk.toFieldIds) ? fk.toFieldIds : [];
      if (fromIds.length === 0 || toIds.length === 0 || fromIds.length !== toIds.length) return;

      const fromColumns = fromIds
        .map((fieldId) => (table.fields || []).find((field) => field.id === fieldId))
        .filter(Boolean)
        .map((field) => quoteIdentifier(dbType, field.code));
      const toColumns = toIds
        .map((fieldId) => (referencedTable.fields || []).find((field) => field.id === fieldId))
        .filter(Boolean)
        .map((field) => quoteIdentifier(dbType, field.code));
      if (fromColumns.length === 0 || fromColumns.length !== toColumns.length) return;

      const rawConstraintName =
        (typeof fk.name === "string" && fk.name.trim())
          ? fk.name.trim()
          : `fk_${table.code || table.name}_${referencedTable.code || referencedTable.name}`;
      const uniqueConstraintName = usedConstraintNames.has(rawConstraintName)
        ? `${rawConstraintName}_${usedConstraintNames.size + 1}`
        : rawConstraintName;
      usedConstraintNames.add(uniqueConstraintName);
      const constraintName = quoteIdentifier(dbType, uniqueConstraintName);
      const referencedTableName = quoteIdentifier(dbType, referencedTable.code);
      defs.push(
        `  CONSTRAINT ${constraintName} FOREIGN KEY (${fromColumns.join(", ")}) REFERENCES ${referencedTableName} (${toColumns.join(", ")})`,
      );
    });

    return defs;
  }

  function getTableScript(model, table, options = {}) {
    const includeForeignKeys = options.includeForeignKeys !== false;
    const dbType = model.dbType;
    const tableName = quoteIdentifier(dbType, table.code);
    const fields = table.fields || [];
    const pkColumns = fields
      .filter((field) => field.primaryKey && !(dbType === "SQLite" && field.autoIncrement))
      .map((field) => quoteIdentifier(dbType, field.code));
    const columnDefs = fields.map((field) => `  ${buildFieldSqlDefinition(field, dbType)}`);

    if (pkColumns.length > 0) {
      columnDefs.push(`  PRIMARY KEY (${pkColumns.join(", ")})`);
    }
    if (includeForeignKeys) {
      columnDefs.push(...buildForeignKeyDefinitions(model, table, dbType));
    }

    let sql = `CREATE TABLE ${tableName} (\n${columnDefs.join(",\n")}\n)`;
    if (dbType === "MySQL 8") {
      const mysqlTail = ["ENGINE=InnoDB", "DEFAULT CHARSET=utf8mb4"];
      if (table.comment) {
        mysqlTail.push(`COMMENT='${escapeSqlLiteral(table.comment)}'`);
      }
      sql += ` ${mysqlTail.join(" ")};`;
    } else if (dbType === "PostgreSQL 14") {
      sql += ";";
      if (table.comment) {
        sql += `\n\nCOMMENT ON TABLE ${tableName} IS '${escapeSqlLiteral(table.comment)}';`;
      }
      fields.forEach((field) => {
        if (!field.comment) return;
        sql += `\nCOMMENT ON COLUMN ${tableName}.${quoteIdentifier(dbType, field.code)} IS '${escapeSqlLiteral(field.comment)}';`;
      });
    } else {
      sql += ";";
    }

    const indexes = Array.isArray(table.indexes) ? table.indexes : [];
    indexes.forEach((indexItem) => {
      if (indexItem.isPrimary) return;
      const fieldCodes = (indexItem.columns || [])
        .map((fieldId) => fields.find((field) => field.id === fieldId))
        .filter(Boolean)
        .map((field) => quoteIdentifier(dbType, field.code));
      if (fieldCodes.length === 0) return;

      const uniquePrefix = indexItem.unique ? "UNIQUE " : "";
      const indexName = quoteIdentifier(dbType, indexItem.name);
      if (dbType === "PostgreSQL 14") {
        const method = (indexItem.method || "btree").toLowerCase();
        sql += `\n\nCREATE ${uniquePrefix}INDEX ${indexName} ON ${tableName} USING ${method} (${fieldCodes.join(", ")});`;
      } else {
        sql += `\n\nCREATE ${uniquePrefix}INDEX ${indexName} ON ${tableName} (${fieldCodes.join(", ")});`;
      }
    });

    return sql;
  }

  Object.assign(root, {
    getTableScript,
  });
})(window);
